# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5884b3da79953ef05d1ebdb95a199cdfc1d6c83fa87b236b6a8279d68e3d80dd8b274867efea4af946346ea461821803b8646b2665818351c2dfb1f1e259d8e5

test:
  secret_key_base: 77d3882f69bc3bd9896548797ace799cc895681029261136b65fad9d122ff166f61086ac0b052b1fcd401ab2eddd52a9f1b3e9b57e66dd5ce2ac62a42417fbfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
